### PR TITLE
Update `mkmovie.py`: cleanup, modernization, and improvements

### PR DESCRIPTION
**Pull request by cgobat**
This PR encompasses a number of updates to the `mkmovie.py` script. It should still be entirely backwards-compatible (i.e. existing workflows will not have to be modified). The changes are summarized as follows:

* Command-line argument parsing: use `argparse` instead of `getopt`
  * Like `getopt`, [`argparse`](https://docs.python.org/3/library/argparse.html) is a part of the Python standard library, but facilitates a higher degree of code readability/clarity/maintainability
* Calling external programs: use `subprocess` instead of `os.system`
  * The [`subprocess`](https://docs.python.org/3/library/subprocess.html) module (also part of the standard library) is preferable to `os.system` calls for [a number of reasons](https://stackoverflow.com/q/44730935/4450498). Even the [`os.system` documentation](https://docs.python.org/3/library/os.html#os.system) itself mentions this.
* Add OpenCV-based movie generation routine as a backup in case `mencoder` fails
  * `mencoder` isn't available on all systems (e.g. Windows), or sometimes has issues. In case it causes an error, this PR adds an alternative [`cv2.VideoWriter`](https://docs.opencv.org/4.x/dd/d9e/classcv_1_1VideoWriter.html)-based pathway for generating movies from the same inputs.
  * Whether or not the script uses `mencoder` or `cv2.VideoWriter` to do the encoding/movie generation is transparent to the user.
  * OpenCV (`cv2`) not being installed is not a problem as long as `mencoder` works.
* General code cleanup and modernization
  * Excess verbosity has been trimmed (e.g. removal of unnecessary loops, more compact logic/control flow, etc.)
  * Make better use of Python's full capabilities (e.g. [f-strings](https://docs.python.org/3/tutorial/inputoutput.html#tut-f-strings) instead of `%`-based formatting, negative indexing instead of `x[len(x)-1]`, etc.)

### CODE REVIEW

**Comment by cgobat** [comment]
@zingale bump

**Comment by cgobat** [comment]
@zingale bump

**Comment by cgobat** [comment]
@zingale bump

**Review by zingale — APPROVED** [review]

**Comment by zingale** [comment]
Hi, thanks for this issue.  I've actually switched from using this script to rendering using ffmpeg, because that seems to give better compatibility on Mac OS.  I've rerendered all the movies here:
https://zingale.github.io/astro_animations/

but I am fine with your changes, and thank you for your contribution

**Pull request merged**
